"""Push a week's workouts to a dedicated "Iron Coach" Google Calendar.

Each workout becomes an all-day event. Events carry a private extended
property (ironcoach_week = Monday date) so re-running for the same week
replaces that week's events instead of duplicating them.

Requires credentials.json (OAuth desktop client) in the project root; the first
run opens a browser for consent and stores token.json next to it. Both files
are gitignored.
"""
from datetime import date, timedelta

from .config import CALENDAR_NAME, GOOGLE_CREDENTIALS_PATH, GOOGLE_TOKEN_PATH

SCOPES = ["https://www.googleapis.com/auth/calendar"]


def _service():
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build

    if not GOOGLE_CREDENTIALS_PATH.exists():
        raise FileNotFoundError(
            f"{GOOGLE_CREDENTIALS_PATH.name} not found - see README 'Google Calendar setup'"
        )
    creds = None
    if GOOGLE_TOKEN_PATH.exists():
        creds = Credentials.from_authorized_user_file(str(GOOGLE_TOKEN_PATH), SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(str(GOOGLE_CREDENTIALS_PATH), SCOPES)
            creds = flow.run_local_server(port=0)
        GOOGLE_TOKEN_PATH.write_text(creds.to_json(), encoding="utf-8")
    return build("calendar", "v3", credentials=creds, cache_discovery=False)


def _get_or_create_calendar(service):
    page = None
    while True:
        resp = service.calendarList().list(pageToken=page).execute()
        for cal in resp.get("items", []):
            if cal.get("summary") == CALENDAR_NAME:
                return cal["id"]
        page = resp.get("nextPageToken")
        if not page:
            break
    created = service.calendars().insert(body={"summary": CALENDAR_NAME}).execute()
    return created["id"]


def _delete_week(service, cal_id, week_start):
    page = None
    deleted = 0
    while True:
        resp = service.events().list(
            calendarId=cal_id, privateExtendedProperty=f"ironcoach_week={week_start}",
            pageToken=page, showDeleted=False, maxResults=250,
        ).execute()
        for ev in resp.get("items", []):
            service.events().delete(calendarId=cal_id, eventId=ev["id"]).execute()
            deleted += 1
        page = resp.get("nextPageToken")
        if not page:
            return deleted


def _event_body(w, plan):
    d = date.fromisoformat(w["date"])
    dur = f"{w['duration_min']} min" if w["duration_min"] else ""
    title = f"{w['emoji']} {w['title']}" + (f" ({dur})" if dur else "")
    lines = [
        f"Intensity: {w['intensity']}",
        f"Duration: {dur}" if dur else None,
        "",
        w["description"],
        "",
        f"Phase: {plan['phase']}{' (deload)' if plan.get('is_recovery') else ''} - "
        f"{plan['weeks_to_race']} weeks to race",
        "Generated by Iron Coach",
    ]
    return {
        "summary": title,
        "description": "\n".join(l for l in lines if l is not None),
        "start": {"date": d.isoformat()},
        "end": {"date": (d + timedelta(days=1)).isoformat()},
        "transparency": "transparent",
        "reminders": {"useDefault": False},
        "extendedProperties": {"private": {"ironcoach_week": plan["week_start"], "ironcoach_sport": w["sport"]}},
    }


def sync_week(plan):
    """Replace the calendar events for plan['week_start'] with the given workouts."""
    service = _service()
    cal_id = _get_or_create_calendar(service)
    _delete_week(service, cal_id, plan["week_start"])
    count = 0
    for w in plan["workouts"]:
        if w["sport"] == "rest":
            continue
        service.events().insert(calendarId=cal_id, body=_event_body(w, plan)).execute()
        count += 1
    return count
